runner/1 Basic Cairo Verifier Runner Setup
HerodotusDev/cairo-verifier pull request #18
Opened 2023-12-22 10:53 UTC by neotheprogramist

2023-12-29 16:33 UTC, tiagofneto requested changes

2023-12-29 16:33 UTC, tiagofneto commented on README.md
Maybe let's move this README to the runner directory

2023-12-29 16:33 UTC, tiagofneto commented on runner/README.md
This README makes more sense in the root of the repo perhaps?

2023-12-29 16:33 UTC, tiagofneto commented on runner/resources/fulloutput.txt
Maybe we should include this resources files in the `.gitignore`? Or are they supposed to serve as examples here?

Seems annoying that every time we will parse new proofs we will have to commit them

2023-12-29 16:33 UTC, tiagofneto commented on runner/resources/parserin.txt
Same comment as the `fulloutput.txt` file

2023-12-29 16:33 UTC, tiagofneto commented on src/lib.cairo
> +fn main(stark_proof: StarkProof) -> (felt252, felt252) {
I think for now it's ok to leave the main function in the main `lib` file as it is quite simple, but if it starts getting more complex we should move it to a separate file

2023-12-30 09:22 UTC, neotheprogramist commented on runner/resources/fulloutput.txt
Sure I agree, the goal of it was to show you the format of the proof files - just to present them

2023-12-30 10:50 UTC, tiagofneto approved these changes

2023-12-30 11:06 UTC, merged